/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class home_example_opdsbrowser_MainActivity */

#ifndef _Included_home_example_opdsbrowser_MainActivity
#define _Included_home_example_opdsbrowser_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef home_example_opdsbrowser_MainActivity_MODE_PRIVATE
#define home_example_opdsbrowser_MainActivity_MODE_PRIVATE 0L
#undef home_example_opdsbrowser_MainActivity_MODE_WORLD_READABLE
#define home_example_opdsbrowser_MainActivity_MODE_WORLD_READABLE 1L
#undef home_example_opdsbrowser_MainActivity_MODE_WORLD_WRITEABLE
#define home_example_opdsbrowser_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef home_example_opdsbrowser_MainActivity_MODE_APPEND
#define home_example_opdsbrowser_MainActivity_MODE_APPEND 32768L
#undef home_example_opdsbrowser_MainActivity_BIND_AUTO_CREATE
#define home_example_opdsbrowser_MainActivity_BIND_AUTO_CREATE 1L
#undef home_example_opdsbrowser_MainActivity_BIND_DEBUG_UNBIND
#define home_example_opdsbrowser_MainActivity_BIND_DEBUG_UNBIND 2L
#undef home_example_opdsbrowser_MainActivity_CONTEXT_INCLUDE_CODE
#define home_example_opdsbrowser_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef home_example_opdsbrowser_MainActivity_CONTEXT_IGNORE_SECURITY
#define home_example_opdsbrowser_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef home_example_opdsbrowser_MainActivity_CONTEXT_RESTRICTED
#define home_example_opdsbrowser_MainActivity_CONTEXT_RESTRICTED 4L
#undef home_example_opdsbrowser_MainActivity_RESULT_CANCELED
#define home_example_opdsbrowser_MainActivity_RESULT_CANCELED 0L
#undef home_example_opdsbrowser_MainActivity_RESULT_OK
#define home_example_opdsbrowser_MainActivity_RESULT_OK -1L
#undef home_example_opdsbrowser_MainActivity_RESULT_FIRST_USER
#define home_example_opdsbrowser_MainActivity_RESULT_FIRST_USER 1L
#undef home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_DISABLE
#define home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_DIALER
#define home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_SHORTCUT
#define home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define home_example_opdsbrowser_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     home_example_opdsbrowser_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_home_example_opdsbrowser_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
